### ISSUE TITLE
400 Client Error: Bad Request for URL

### ISSUE THREAD

**Issue by whoub2020** [c-okelly/anki-remote-decks#98] opened 2021-08-23 20:15 UTC
I get an error when trying to create cards from a Google Docs file. This error appears on new decks, documents I've previously been able to convert, and on both Anki 2.1.44 and 2.1.46
[
<img width="767" alt="Screen Shot 2021-08-23 at 15 13 01" src="https://user-images.githubusercontent.com/89420413/130513061-66ce0a01-ba2d-4398-b412-829e9d3d4d42.png">
](url)

**Comment by BrunhildeVanDeBouwe** [comment] 2021-08-24 07:48
I get the same error message - but if I delete all the images in google docs, it works fine.

**Comment by DanielB1235** [comment] 2021-08-24 08:11
Same error message with decks with pictures. Text only decks still work fine.

**Comment by hjordisasta** [comment] 2021-08-30 13:41
I have the same issue, have not been able to solve it

**Comment by leoprob98** [comment] 2021-08-30 15:14
I have the same problem.

**Comment by c-okelly** [comment] 2021-08-30 21:08
It seems that Google must have changed the URL for images. Will have a proper look into it this evening

**Comment by c-okelly** [comment] 2021-08-30 21:11
There has not been much activity recently as there was a lot of issue related to breaking API changes within Anki. 

I will make sure to investigate this though since it seems more likely it is on the Google side of it

**Comment by hjordisasta** [comment] 2021-08-31 15:25
> There has not been much activity recently as there was a lot of issue related to breaking API changes within Anki.
> 
> I will make sure to investigate this though since it seems more likely it is on the Google side of it

Is there any way that you know of to make it work for the time being? 

Thanks in advance,

**Comment by c-okelly** [comment] 2021-08-31 19:42
Only real solution would be to remove all the image or manually patch the code but I don't know just yet what the issue is the with the URLs.

I might not be till later this week I can actually dig into it

**Comment by c-okelly** [comment] 2021-09-02 06:46
Ok I have gotten to the bottom of what the issue is and it should not be a big fix. Will hopefully push the fix tomorrow once I do some more testing!

**Comment by leoprob98** [comment] 2021-09-02 14:46
Thank you so much! @c-okelly

**Comment by c-okelly** [comment] 2021-09-06 07:53
Sorry will get it done today

**Comment by c-okelly** [comment] 2021-09-07 16:15
Ok have a working building but just doing some more testing before I push will def be completed by Wednesday this week!

**Comment by c-okelly** [comment] 2021-09-09 17:51
This issue should be closed by 9c06a75ec5b5a7e1142bbd0b3e73d81a01208bd6 . I have added a new build to the ankiweb addon so should be able to update it via the normal way in Anki.

Let me know if there are any existing issues

**Closed by c-okelly** 2021-09-09 17:51 UTC
Labels: bug

**Comment by c-okelly** [comment] 2021-09-09 17:52
Also reading over some of the code I wrote a few years ago was a trip. None of it would pass a code review i would do now!

**Comment by hjordisasta** [comment] 2021-09-10 09:41
THANK YOU!! I'm so so glad all my decks work now hahah.
Do you think there will be an update on the text formatting soon - so bold/italics/underlining (+colors) would sync and appear on the cards in anki too?

**Comment by BrunhildeVanDeBouwe** [comment] 2021-09-10 14:09
Thanks a lot!!!

**Comment by leoprob98** [comment] 2021-09-10 15:16
Thank you so much! @c-okelly

**Comment by francisbeynon** [comment] 2021-09-19 16:54
> This issue should be closed by [9c06a75](https://github.com/c-okelly/anki-remote-decks/commit/9c06a75ec5b5a7e1142bbd0b3e73d81a01208bd6) . I have added a new build to the ankiweb addon so should be able to update it via the normal way in Anki.
> 
> Let me know if there are any existing issues

Hi @c-okelly ,

Thank you for working on this bug and update. Unfortunately I still can't see images when using the remote anki deck. I'm using a macbook pro and ipad. Is there still an image issue with apple products? Many thanks
