### ISSUE TITLE
ascii error

### ISSUE THREAD

**Issue by fneurohr22** [c-okelly/anki-remote-decks#40] opened 2020-01-25 03:12 UTC
i was syncing and got this error text “The error was 'ascii' codec can't encode character '\xbf' in position 27: ordinal not in range(128).“

i can provide the published version of the google docs for you to check it out to see if we can fix this. it be nice to do this privately though

thx in advance

**Comment by c-okelly** [comment] 2020-01-25 06:10
Are you one Mac Os Catalina by any chance? or some other version of mac?

**Comment by fneurohr22** [comment] 2020-01-25 18:19
yep, MacOS Catalina Version: 10.15.2 (19C57)

**Comment by fneurohr22** [comment] 2020-01-25 18:23
I am very worried, as well as my peer. As you know we use remote decks to study for our classes and we will be soon having a test. is there a way to fix this asap? you need me to give you the published link of the remote deck??

**Comment by c-okelly** [comment] 2020-01-25 19:22
Yep this is related to another issue already open. It appears that in the upgrade to  10.15.2 it has broken the addon for some reason. Thought I don't understand how.

I'm trying to get a OSx vm to test on as unfortunately I do not have a mac laptop but I am working on it

**Comment by c-okelly** [comment] 2020-01-25 19:48
I'm going to close this as it is a duplicate of #37

**Closed by c-okelly** 2020-01-25 19:48 UTC
